### ISSUE TITLE
import: add typing

### ISSUE THREAD

**Issue by daiyam** [kaoscript/kaoscript#64]
```
import 'benchmark' => Benchmark
import 'fs'
import 'chevrotain' => {
	func createToken
	class Lexer
	class Parser
	class Token
}
```
instead of
```
import * as Benchmark from benchmark
import * as fs from fs
import createToken, Lexer, Parser, Token from chevrotain
```

**Comment by bd82** [comment]
Hi @daiyam 

Are you using or intending to use Chevrotain? I can't find any other reference to it in this repo.

Thanks.

**Comment by daiyam** [comment]
Hi @bd82 

Yes, I'm intending use Chevrotain to support the future `macro` syntax.

Thx

**Comment by bd82** [comment]
Cool, Don't be shy and open issues in the Chevrotain repo if needed (I'm the main author) 😄
